In [1]:
data={
    'Tid':['1','2','3','4','5','6','7','8','9','10'],
    'Refund':['Yes','No','No','Yes','No','No','Yes','No','No','No'],
    'Marital Status':['Single','Married','Single','Marrried','Divorced','Married','Divorced','Single','Married','Single'],
    'Taxable Income':['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k'],
    'Cheat':['No','No','No','No','Yes','No','No','Yes','No','Yes']
}

In [7]:
import pandas as pd
df=pd.DataFrame(data)
print(df)

  Tid Refund Marital Status Taxable Income Cheat
0   1    Yes         Single           125k    No
1   2     No        Married           100k    No
2   3     No         Single            70k    No
3   4    Yes       Marrried           120k    No
4   5     No       Divorced            95k   Yes
5   6     No        Married            60k    No
6   7    Yes       Divorced           220k    No
7   8     No         Single            85k   Yes
8   9     No        Married            75k    No
9  10     No         Single            90k   Yes

Q.2 From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.

In [13]:
print(df.loc[[0,4,7,8]])

  Tid Refund Marital Status Taxable Income Cheat
0   1    Yes         Single           125k    No
4   5     No       Divorced            95k   Yes
7   8     No         Single            85k   Yes
8   9     No        Married            75k    No

Q.3 Navigate the DataFrame and do the following task for the table created in question 1:
1. Select row from index 3 to 7.
2. Select row from index 4 to 8, and column 2 to 4.
3. Select all rows with column index 1 to 3 (include index 3 during selection).

In [14]:
print(df.loc[3:7])

  Tid Refund Marital Status Taxable Income Cheat
3   4    Yes       Marrried           120k    No
4   5     No       Divorced            95k   Yes
5   6     No        Married            60k    No
6   7    Yes       Divorced           220k    No
7   8     No         Single            85k   Yes

In [16]:
print(df.iloc[4:9,2:5])

  Marital Status Taxable Income Cheat
4       Divorced            95k   Yes
5        Married            60k    No
6       Divorced           220k    No
7         Single            85k   Yes
8        Married            75k    No

In [21]:
print(df.iloc[:,1:4])

  Refund Marital Status Taxable Income
0    Yes         Single           125k
1     No        Married           100k
2     No         Single            70k
3    Yes       Marrried           120k
4     No       Divorced            95k
5     No        Married            60k
6    Yes       Divorced           220k
7     No         Single            85k
8     No        Married            75k
9     No         Single            90k

Q.4 Read a csv file and display its first five rows.
Note-: Download dataset from https://www.kaggle.com/datasets/uciml/iris)

In [28]:
df1=pd.read_csv('Iris.csv')
print(df1.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Q.5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the
result.

In [29]:
df1.drop(index=4,columns=df1.columns[3],inplace=True)
print(df1)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

Q.6 Create a sample dataset (employees.csv) containing information about employees in
a company.

In [50]:
dataa={
    'Employee_ID':['101','102','103','104','105'],
    'Name':['Alice','Bob','Charlie','Diana','Edward'],
    'Department':['HR','IT','IT','Marketing','Sales'],
    'Age':['29','34','41','28','38'],
    'Salary':['50000','70000','65000','55000','60000'],
    'Years_of_Experience':['4','8','10','3','12'],
    'Joining_Date':['2020-03-15','2017-07-19','2013-06-01','2021-02-10','2010-11-25'],
    'Gender':['Female','Male','Male','Female','Male'],
    'Bonus':['5000','7000','6000','4500','5000'],
    'Rating':['4.5','4.0','3.8','4.7','3.5']
}

In [51]:
df3=pd.DataFrame(dataa)
df3.to_csv('employees.csv',index=False)

In [52]:
df4=pd.read_csv('employees.csv')
df4.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

a) Shape (number of rows and columns) of the DataFrame.

In [53]:
df4.shape

(5, 10)

b) Summary of the DataFrame that includes the data types and non-null counts for
each column.

In [54]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

c) Generate descriptive statistics.

In [55]:
print(df4.describe())

       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000

d) Display the first 5 rows and last 3 rows of the dataset.

In [56]:
print(df4.head())
print(df4.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

e) Calculate the following statistics from the dataset:
i. The average salary of employees.
ii. The total bonus paid to all employees.
iii. The youngest employee's age.
iv. The highest performance rating

In [57]:
# i. The average salary of employees.
print(df4['Salary'].mean())

60000.0

In [58]:
# ii. The total bonus paid to all employees.
print(df4['Bonus'].sum())

27500

In [59]:
#iii. The youngest employee's age.
print(df4['Age'].min())

28

In [60]:
#iv. The highest performance rating
print(df4['Rating'].max())

4.7

f) Sort the DataFrame by the Salary column in descending order

In [61]:
print(df4.sort_values('Salary',ascending=False))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

g) Add a new column that categorizes employees based on their performance rating:
i. Excellent for ratings >= 4.5
ii. Good for ratings >= 4.0 but < 4.5
iii. Average for ratings < 4.0

In [62]:
performance=[]
for rating in df4['Rating']:
  if rating>=4.5:
    performance.append('Excellent')
  elif rating>=4.0 and rating<4.5:
    performance.append('Good')
  else:
    performance.append('Average')
df4['Performance']=performance
print(df4)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance
0   2020-03-15  Female   5000     4.5   Excellent
1   2017-07-19    Male   7000     4.0        Good
2   2013-06-01    Male   6000     3.8     Average
3   2021-02-10  Female   4500     4.7   Excellent
4   2010-11-25    Male   5000     3.5     Average

h) Identify missing values in the DataFrame.

In [63]:
df4.isnull().sum()

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

i) Rename the Employee_ID column to ID.

In [64]:
df4.rename(columns={'Employee_ID':'ID'},inplace=True)
df4

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

j) Find all employees who:
i. Have more than 5 years of experience.
ii. Belong to the IT department.

In [65]:
#i. Have more than 5 years of experience
print(df4[df4['Years_of_Experience']>5])

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance
1   Male   7000     4.0        Good
2   Male   6000     3.8     Average
4   Male   5000     3.5     Average

In [66]:
#ii. Belong to the IT department.
print(df4[df4['Department']=='IT'])

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance
1   Male   7000     4.0        Good
2   Male   6000     3.8     Average

k) Modify the dataset by adding a new column, Tax, which deducts 10% of the
Salary.

In [68]:
df4['Tax'] = df4['Salary'] * 0.10
print(df4)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance     Tax
0  Female   5000     4.5   Excellent  5000.0
1    Male   7000     4.0        Good  7000.0
2    Male   6000     3.8     Average  6500.0
3  Female   4500     4.7   Excellent  5500.0
4    Male   5000     3.5     Average  6000.0

l) Save the modified DataFrame (with added columns) to a new CSV file

In [69]:
df4.to_csv('modified_employees.csv', index=False)